# fly.toml app configuration file generated for novorender-proving-ground on 2023-10-22T15:22:47+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "novorender-proving-ground"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8043"

[[services]]
  protocol = "tcp"
  internal_port = 8043
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 150
    soft_limit = 100

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
